### ISSUE TITLE
Kolka drops too early

### ISSUE THREAD

**Issue by Hive89** [JK-Rolling/DuinoCoinI2C_RPI#12]
Thanks for updating to Version 3! Unfortunately Kolka drops are wrong. The first (Arduino) miner has 100% the second 96%,.... should be 100% for the first 4 miners and then dropping by 4 %. Could you look at it? Thanks.

**Comment by JK-Rolling** [comment]
Kolka is server side. There's nothing we can do to change that directly. Try raise issue ticket in official duino-coin
