### ISSUE TITLE
Rejected (Outdated miner)

### ISSUE THREAD

**Issue by olinitesh** [JK-Rolling/DuinoCoinI2C_RPI#13]
Unable to get any accepted one. It just says Rejected(Outdated miner). Is it due to server issues or anything else? Internet works fine. Ping works fine.

**Comment by Hive89** [comment]
Hi, I have the same problem since about 5-6h

**Comment by JMPP2** [comment]
Hi, I have the same problem

**Comment by Hive89** [comment]
problem has been fixed, see :https://github.com/ricaun/DuinoCoinI2C/issues/77

**Comment by JK-Rolling** [comment]
this is server side issue. root caused to version regex. closing as nothing to do from my side
