### ISSUE TITLE
Error on complile

### ISSUE THREAD

**Issue by teomalex** [JK-Rolling/DuinoCoinI2C_RPI#15]
Arduino uno/nano...328
Arduino\libraries\TinyWireS\TinyWireS.cpp:71:25: error: 'USIPF' was not declared in this scope

Arduino\libraries\TinyWireM\USI_TWI_Master.cpp:358:23: error: 'USIPF' was not declared in this scope

**Comment by JK-Rolling** [comment]
use [DuinoCoin_RPI_Tiny_Slave](https://github.com/JK-Rolling/DuinoCoinI2C_RPI/tree/main/DuinoCoin_RPI_Tiny_Slave) for uno/nano. [DuinoCoin_Tiny_Slave_trinket](https://github.com/JK-Rolling/DuinoCoinI2C_RPI/tree/main/DuinoCoin_Tiny_Slave_trinket) is solely for Adafruit Trinket
