### ISSUE TITLE
nano not starting after reboot

### ISSUE THREAD

**Issue by sprokkie** [JK-Rolling/DuinoCoinI2C_RPI#16]
I updated the raspberry to V3.0 with the ginclone command
i updated the 10 nano. If tghe pi is running and i ad them 1 at the time it worked fine.
If i do a reboot the pi cannot find the nano's anymore, 

Any thoughts what i do wrong?

**Comment by JK-Rolling** [comment]
is the issue still happening?
what is the error message when that happened?

**Comment by sprokkie** [comment]
i forgot to update the nano's

**Comment by JK-Rolling** [comment]
thanks for the answer. I'll proceed to close the case.
