### ISSUE TITLE
 local variable 'i2c_rdata' referenced before assignment

### ISSUE THREAD

**Issue by tbillion** [JK-Rolling/DuinoCoinI2C_RPI#17]
04:23:43.290381 DEBUG: 0a: [Errno 121] Remote I/O error
04:23:43.298230 DEBUG: 0a: Reading result from the board
04:23:43.420071 DEBUG: 0a: [Errno 121] Remote I/O error
04:23:43.429786 DEBUG: 0a: Retrying data read: local variable 'i2c_rdata' referenced before assignment
04:23:43.439259 DEBUG: 0a: Sending job to the board
04:23:43.447743 DEBUG: 0a: Job: 4fdbe284673c1b2bbc86762d225634e20c3fa8f6,160d4ab63735e127bacb14d41eab21424252db7c,6,

04:23:43.550828 DEBUG: 0a: [Errno 121] Remote I/O error

**Comment by JK-Rolling** [comment]
the worker is which board? e.g. nano/pico

**Comment by tbillion** [comment]
Pico

**Comment by JK-Rolling** [comment]
have you try this workaround?
https://github.com/JK-Rolling/DuinoCoinI2C_RPI#arduino-mbed-os-rp2040-version-280

**Comment by tbillion** [comment]
Yes . I did that

. I assume that's another problem entirely however that hack doesn't stop
it from hanging the bus.

And it doesn't fix the variable thing . You may have fixed the variable
thing because when I re down loaded last night it was no longer an issue.

The hanging the bus thing on the mbed platform is a very valid issue
however

I have attempted this code on a miner and it will start the first one but
it will not run after that it just infinitely times out

**Comment by JK-Rolling** [comment]
maybe try fallback to mbed os 2.3.1 ?

**Comment by tbillion** [comment]
Ok bricked one environment trying to fall back to mbed 2.3.1 rolled another environment back successfully and now all is functioning . Sorta.

Is the status quo going to be to have to run it on mbed 2.3.1? 

Is there a way to set the difficulty in the main script so that I don't have a bunch of incorrect difficulty errors. It will run for a few minutes and then it will say incorrect difficulty then as it continues it will go for a while then right back to difficulty incorrect errors , my accuracy is horrible like in the high 30% I only have 10 picos hooked to the back plane and there is room for 32 is this a timing issue?
![16482374124993675005524943410360](https://user-images.githubusercontent.com/16172731/160190673-88c7ecdd-6907-4d2f-a654-0e2675ff20a8.jpg)
![Uploading 1648237451782215699411092151591.jpg…]()

**Comment by tbillion** [comment]
![16482376020843194552821821224888](https://user-images.githubusercontent.com/16172731/160191046-8b6e7405-ac01-4d85-a9bf-156f873fc82f.jpg)

**Comment by JK-Rolling** [comment]
the Pico sketch no longer use mbed now. try update the Pico to latest sketch and use the latest Python script.
the update enabled dual core functionality and better error correction

**Comment by JK-Rolling** [comment]
no response. closing.

**Comment by tbillion** [comment]
Nah it still didn't work . Not sure what 8t 8s not solved
