### ISSUE TITLE
bus choice

### ISSUE THREAD

**Issue by panayotovip** [JK-Rolling/DuinoCoinI2C_RPI#2]
how i cant specify device bus ?
i need to use /dev/i2c-0 but it is show me only what i have on /dev/i2c-1

**Comment by JK-Rolling** [comment]
I'll look into this. see whether is there possibility of using both simultaneously

**Comment by panayotovip** [comment]
I thing may by is better option is to have some parameter to point exact bus.
In others configurations other devices (raspberries) may have other devices (on theirs i2c) with other purposes.
Using multiple bus may appear or create bugs of normal work of device (unexpected reboots, freezes etc. )

Add: in other devices (raspberries) is possible to have i2c bus to be different number from 0 or 1.

**Comment by JK-Rolling** [comment]
good input. That should improve stability as well. I'll give the code some test before releasing, so expect some delay

**Comment by JK-Rolling** [comment]
enhancement implemented

**Comment by panayotovip** [comment]
great work. thanks.
