### ISSUE TITLE
Pullup Resitirs for SDA/SCL

### ISSUE THREAD

**Issue by SanwebGit** [JK-Rolling/DuinoCoinI2C_RPI#20]
You wrote: "LLC is required if worker and host is operating at different voltage. 4k7 pullup resistors for SDA/SCL pins are strongly recommended if host do not have it built-in."

When i use an ESP8266 or ESP32 as Master with 5V, must i add pullup 4k7 resistors between SDA -> VCC and SCL -> VCC, or have the ESP8266/ESP32 10K resistors builtin?

**Comment by JK-Rolling** [comment]
if you don't see i2c communication error (data corruption), then resistors are optional

**Comment by JK-Rolling** [comment]
closing
