### ISSUE TITLE
Auto-start AVR_Miner_RPI.py

### ISSUE THREAD

**Issue by rtbon** [JK-Rolling/DuinoCoinI2C_RPI#21]
Hi, I would like to automate the mining on pi startup.
I've edit the crontab with a new line :
`@reboot screen -dm bash -c "cd ~/DuinoCoinI2C_RPI; python3 ./AVR_Miner_RPI.py"`

… But nothing happen on reboot.

An other problem, from ssh on my Mac I can't detach from the screen session while pressing `ctrl + a` and then `d`

Can you help me ?
Thank you !

**Comment by JK-Rolling** [comment]
what do you see when running this command manually?
`cd ~/DuinoCoinI2C_RPI; python3 ./AVR_Miner_RPI.py`

**Comment by JK-Rolling** [comment]
also found this "using screen on mac os". it maybe helpful
http://www.kinnetica.com/2011/05/29/using-screen-on-mac-os-x/#:~:text=Detaching%20and%20Reattaching%20Your%20Screen%20Session&text=Type%20Ctrl%2Da%20d%20to%20detach%20from%20your%20screen%20session.

**Comment by JK-Rolling** [comment]
closing
