### ISSUE TITLE
DuinoCoin_ATTiny_Slave.ino with ESP32

### ISSUE THREAD

**Issue by SanwebGit** [JK-Rolling/DuinoCoinI2C_RPI#22]
Can i use the File "[DuinoCoin_ATTiny_Slave](https://github.com/JK-Rolling/DuinoCoinI2C_RPI/tree/main/DuinoCoin_ATTiny_Slave)" with an ESP32 File "[DuinoCoin_Esp_Async_Master.ino](https://github.com/JK-Rolling/DuinoCoinI2C/blob/main/DuinoCoin_Esp_Async_Master/DuinoCoin_Esp_Async_Master.ino)" from your other Repository?

**Comment by JK-Rolling** [comment]
I'll look into enhancing the esp sketch

**Comment by JK-Rolling** [comment]
ESP sketch initial enhancement done. I did some quick test and seems to be working fine. Please get it from the tip and let me know if there is any issue
https://github.com/JK-Rolling/DuinoCoinI2C

**Comment by JK-Rolling** [comment]
closing
