### ISSUE TITLE
Problem ESP8266 i2c Nano 

### ISSUE THREAD

**Issue by Magikit** [JK-Rolling/DuinoCoinI2C_RPI#23]
I have a problem with esp8266 monitoring the port and esp only reports such stamps, how to fix it?
[https://ibb.co/nMkKnC3](url)

**Comment by JK-Rolling** [comment]
somehow I'm not able to open the link, but I believe you're referring to the enhancement needed on the esp sketch from case https://github.com/JK-Rolling/DuinoCoinI2C_RPI/issues/22

**Comment by JK-Rolling** [comment]
closing dup case. Please monitor https://github.com/JK-Rolling/DuinoCoinI2C_RPI/issues/22 for latest development
