### ISSUE TITLE
negative mining

### ISSUE THREAD

**Issue by NoNameNoCry** [JK-Rolling/DuinoCoinI2C_RPI#24]
Hi!
@JK-Rolling how are you doing?
I ran into an interesting problem that after an hour of work, my farm began to dig at a loss)) Can you help me?)
![Снимок](https://user-images.githubusercontent.com/104968373/190916588-f2da0781-3159-4965-b570-61bc6bb29ae3.JPG)

Balance 3 hours ago 2584.00371871

![Снимок1](https://user-images.githubusercontent.com/104968373/190916595-3ebf9c70-1e7d-43c8-9342-493ce80e10bd.JPG)

**Comment by NoNameNoCry** [comment]
![image](https://user-images.githubusercontent.com/104968373/192148195-c25ef75d-abea-4130-a87f-f664b578b7f3.png)
Help me pls

**Comment by JK-Rolling** [comment]
please email to duino.coin <at> gmail.com or ask in duino-coin discord about your issue. I believe the owner might be able to help you there. closing as I do not have control over the issue
