### ISSUE TITLE
Newcode release 3.5

### ISSUE THREAD

**Issue by Pheal22** [JK-Rolling/DuinoCoinI2C_RPI#27]
I have been mining quite successfully with the RPI Pico mining rig for sometime now and was wondering if there will be any update on the code to reflect the new 3.5 release on the Duino site?  I see that the Pico mining rig software uses v3.3 so there is no issue at the moment but also see that there is an efficiency increase with the new  v3.5.

**Comment by JK-Rolling** [comment]
although the hashrate increased, but several workers reported issue where Kolka assigned incorrect difficulty level. 
Anyway, I'll look into incorporating the enhancement soon

**Comment by Pheal22** [comment]
No problem, just saw the 3.3 upgrade and using that now – all OK.  Many thanks for all your hard work, really love the I2C rig!

**Comment by JK-Rolling** [comment]
I2C master software updated to 3.5. Thank you and closing
