### ISSUE TITLE
arduino.h -> Arduino.h

### ISSUE THREAD

**Issue by PSLLSP** [JK-Rolling/DuinoCoinI2C_RPI#28]
UNIX like OS are case sensitive and line that tries to include file `arduino.h` is source of trouble
```
#include <arduino.h>
```

It should be `#include <Arduino.h>`

See https://github.com/revoxhere/duino-coin/issues/1697

**Comment by Grantrocks** [comment]
Thank you for that. I couldnt figure out why it wasnt compiling.

**Comment by Grantrocks** [comment]
Thank you for that. I couldnt figure out why it wasnt compiling.
