### ISSUE TITLE
not detact i2c device

### ISSUE THREAD

**Issue by mahesh1987-16** [JK-Rolling/DuinoCoinI2C_RPI#5]
my RP4 8GB and RP ZERO W not working in either of them
Itried in all ways

**Comment by JK-Rolling** [comment]
is this still hapening with the latest vesion?

**Comment by Hive89** [comment]
i had the same problem today with the latest version. seems like my RPi0W does not see any I2C Addresses lower than 0x08. 
Change #define I2CS_START_ADDRESS 3 to #define I2CS_START_ADDRESS 8 in DuinoCoin_Wire.ino and it works just fine.

**Comment by JK-Rolling** [comment]
thanks for the useful info. closing.
