### ISSUE TITLE
Rpi pico compaitabilty issue.

### ISSUE THREAD

**Issue by AbbosMG** [JK-Rolling/DuinoCoinI2C_RPI#9]
Hello! I have been trying to use RPI Pico instead of the Arduino. When I attempt to upload the slave sketch the error pops up saying that the RPI Pico is not compatible with the ArduinoUniqueID library. Could you help me, please!

**Comment by JK-Rolling** [comment]
RPi Pico support added. I'm getting ~10KH/s. Please give it a try

**Comment by AbbosMG** [comment]
Thank you, I'll try n see
